# Generated by Django 2.0.13 on 2019-05-01 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carrier',
            name='mc_number',
            field=models.CharField(max_length=8),
        ),
    ]
