# Generated by Django 2.0.13 on 2019-04-14 17:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Carrier',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mc_number', models.CharField(max_length=12)),
            ],
        ),
        migrations.AddField(
            model_name='shipper',
            name='is_carrier',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='shipper',
            name='is_shipper',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='carrier',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
