# Generated by Django 2.0.13 on 2019-04-24 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Load',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pickup_date', models.DateField()),
                ('ref', models.CharField(max_length=200)),
                ('origin_city', models.CharField(max_length=200)),
                ('destination_city', models.CharField(max_length=200)),
                ('shipper_price', models.FloatField()),
                ('carrier_price', models.FloatField()),
            ],
        ),
    ]
