# Generated by Django 2.0.13 on 2019-04-24 22:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
        ('load', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='load',
            name='carrier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='carrier', to='users.Carrier'),
        ),
        migrations.AddField(
            model_name='load',
            name='dropped_by',
            field=models.ManyToManyField(related_name='dropped_by', to='users.Carrier'),
        ),
        migrations.AddField(
            model_name='load',
            name='shipper',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='shipper', to='users.Shipper'),
        ),
    ]
