# Generated by Django 2.0.13 on 2019-04-02 03:15

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('load', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='load',
            name='pickup_date',
            field=models.DateField(default=datetime.datetime(2019, 4, 2, 0, 15, 42, 979814)),
        ),
    ]
