# Generated by Django 2.1.7 on 2019-03-20 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('load', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='load',
            name='price',
            field=models.FloatField(),
        ),
    ]
