# Generated by Django 2.0.13 on 2019-04-02 03:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('load', '0002_auto_20190402_0015'),
    ]

    operations = [
        migrations.AlterField(
            model_name='load',
            name='pickup_date',
            field=models.DateField(),
        ),
    ]
