# Generated by Django 2.0.13 on 2019-04-03 12:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('load', '0003_auto_20190402_0022'),
    ]

    operations = [
        migrations.AlterField(
            model_name='load',
            name='carrier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='carrier', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='load',
            name='shipper',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='shipper', to=settings.AUTH_USER_MODEL),
        ),
    ]
