# Generated by Django 2.1.7 on 2019-03-31 22:47

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('load', '0003_auto_20190331_1946'),
    ]

    operations = [
        migrations.AlterField(
            model_name='load',
            name='pickup_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
