# Generated by Django 2.0.13 on 2019-04-10 00:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('load', '0004_auto_20190403_0947'),
    ]

    operations = [
        migrations.CreateModel(
            name='DroppedLoads',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('carrier', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('load', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='load.Load')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='droppedloads',
            unique_together={('load', 'carrier')},
        ),
    ]
