# Generated by Django 2.0.13 on 2019-04-12 20:43

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('load', '0005_auto_20190409_2130'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='droppedloads',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='droppedloads',
            name='carrier',
        ),
        migrations.RemoveField(
            model_name='droppedloads',
            name='load',
        ),
        migrations.AddField(
            model_name='load',
            name='dropped_by',
            field=models.ManyToManyField(related_name='droped_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='DroppedLoads',
        ),
    ]
