# Generated by Django 2.0.13 on 2019-04-14 17:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '__latest__'),
        ('load', '0006_auto_20190412_1743'),
    ]

    operations = [
        migrations.AlterField(
            model_name='load',
            name='carrier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='carrier', to='users.Carrier'),
        ),
        migrations.AlterField(
            model_name='load',
            name='dropped_by',
            field=models.ManyToManyField(related_name='dropped_by', to=settings.AUTH_USER_MODEL),
        ),
    ]
