# Generated by Django 2.0.13 on 2019-04-15 00:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('load', '0007_auto_20190414_1722'),
    ]

    operations = [
        migrations.AlterField(
            model_name='load',
            name='dropped_by',
            field=models.ManyToManyField(related_name='dropped_by', to='users.Carrier'),
        ),
    ]
