# Generated by Django 2.0.13 on 2019-04-16 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('load', '0008_auto_20190414_2151'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='load',
            name='price',
        ),
        migrations.AddField(
            model_name='load',
            name='carrier_price',
            field=models.FloatField(default=2),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='load',
            name='shipper_price',
            field=models.FloatField(default=2.0),
            preserve_default=False,
        ),
    ]
